% segTypeGlobP contains all behaviors that are of interest in summary plots
% the row index is the global code for that behavior
segTypeGlobP={...
    'immobile',        [.8 .4 .1],  's';...
    'exploring',       [.5 1 .5],   'o';...      
    'immobile_drug',   [.5 .2 .3],  's';...
    'exploring_drug',  [.5 1 .5]*.6,   'o';...
    'immobile_recov',  [1 .6 .4],  's';...
    'exploring_recov', [.6 1 .8],   'o';...
    'grooming',        [.5 .4 1],  '^';...
    'undef',           [.7 .7 .7],  'o';...    
};
