% bar plots
labelscale('fontSz',6.5,'scaleFac',.34,'lineW',.7,'markSz',5); 
% this one for the somewhat larger lag plots
labelscale('fontSz',8,'scaleFac',.42,'lineW',1,'markSz',4.5); 
% this one for effect sizes
labelscale('fontSz',8,'scaleFac',.42,'lineW',.6,'markSz',2.5); 


rFn='\intermediate_data\out_combine_r';
figSubName='tenyr';
projSubDir='beta3_wtko';

plotStyle='subjects';
plotStyle='barhh';
% plotStyle='symb';


printas='-djpeg97';
printas='-dpsc2';
% printas=[];

statMeth='rm_anova2';
statMeth='anovan';
statMeth='curveFit_FTest';
% statMeth='effect_size';

load(['d:\_data\rmouse\ten-years\beta3_wtko', rFn]);

set_idv;

rv={...
  'thNegPeakCvIPIMn_auto';...
  'thNegPeakCvAMn_auto';...
  'gaePosPeakCvIPIMn_auto';...
  'gaePosPeakCvAMn_auto';...
  'thCCPosPeakDecayMn_auto';...
  'rawThPEMn_auto';...
  'rawGaPEMn_auto';...
  'rawGaCentroidMn_auto';...
  'rawPPeakMn_auto';...
  'rawPPeakTMn_auto';...
  'gaeThNarrowPEMn_auto';...
  'rawCohMnTh_cross';...
  'thCCPeakTMn_cross';...
  'thCCPeakMn_cross';...
  'gaeCCPeakTMn_cross';...
  'thCCPeakPhaseMn_cross';...
  'gaeCCPeakTMn_cross';...
  'gaeCCPeakPhaseMn_cross';...
  'thgaeCCPeakTMn_auto';...
  'thgaeCCPeakPhaseMn_auto';...
  'thgaeCCPeakMn_auto';...
  'thgaeCCZScore_auto';...
  'rawgaeCohPeak_auto';...
  'thgaeCCPeakTStd_auto';...
  'thCCPeakTStd_cross';...
  'gaeCCPeakTStd_cross';...
};

rv={...
   'thgaeCCPeakMn_auto';...
   'gaeThPEMn_auto';...   
  };

rdeal(rFn,idv,statMeth,'curRv',rv,'figSubName',figSubName,...
  'projSubDir',projSubDir,'plotStyle',plotStyle,'printas',printas);