function rmouse_rcleanup
% ** function rmouse_rcleanup
% delete/rename outdated fields from results structure r

global r

rfields={...
    ['NegPeakCvA'],...
    ['NegPeakCvAMn'],...
    ['NegPeakCvAStd'],...
    ['NegPeakCvIPI'],...
    ['NegPeakCvIPIMn'],...
    ['NegPeakCvIPIStd'],...
    ['PosPeakCvA'],...
    ['PosPeakCvAMn'],...
    ['PosPeakCvAStd'],...
    ['PosPeakCvIPI'],...
    ['PosPeakCvIPIMn'],...
    ['PosPeakCvIPIStd'],...
    };
for g=1:length(rfields)
  if isfield(r,['theta' rfields{g}])
    r=rmfield(r,['theta' rfields{g}]);
  end
  if isfield(r,['gammaEnv' rfields{g}])
    r=rmfield(r,['gammaEnv' rfields{g}]);
  end
end




% ---- nov 2006: remove raw-gae coherence fields in small letters
rfields={...
  'rawgaecoh',...
  'rawgaecohPeak',...
  'rawgaecohPeakF',...
  'rawgaecohTh',...
  };
for g=1:length(rfields)
  if isfield(r,rfields{g})
    r=rmfield(r,rfields{g});
  end
end

% ---- jan 2006: remove power in bands derived from averaged psds
rfields={...
  'rawPMnDeP',...
  'rawPMnThP',...
  'rawPMnThNarrowP',...
  'rawPMnBeP',...
  'rawPMnGaP',...
  'rawPMnRiP',...
  };
try
  % test if one of the above exists..
  if isfield(r,rfields{1})
    r=rmfield(r,rfields);
  end
catch
  for g=1:length(rfields)
    if isfield(r,rfields{g})
      r=rmfield(r,rfields{g});
    end
  end
end

% ---- july 2005: coherence for theta narrow renamed
rfields={...
  'rawCohMnTh_narrow',...
  'rawCohStdTh_narrow',...
  'gaeCohMnTh_narrow',...
  'gaeCohStdTh_narrow',...
};
% instead of removing one field at a time, by default do all at once
try
  % test if one of the above exists..
  if isfield(r,rfields{1})
    r=rmfield(r,rfields);
  end
catch
  for g=1:length(rfields)
    if isfield(r,rfields{g})
      r=rmfield(r,rfields{g});
    end
  end
end

% ---- feb 2005: the 'all peaks' fields for thgaeCC and detheCC
rfields={...
  'detheCCAllPeak',...
  'detheCCAllPeakT',...
  'thgaeCCAllPeak',...
  'thgaeCCAllPeakT',...
};
% instead of removing one field at a time, by default do all at once
try
  % test if one of the above exists..
  if isfield(r,rfields{1})
    r=rmfield(r,rfields);
  end
catch
  for g=1:length(rfields)
    if isfield(r,rfields{g})
      r=rmfield(r,rfields{g});
    end
  end
end
  

