function [rv,rvix,rv_commented]=set_rv(q)
% ** function [rv,rvix,rv_commented]=set_rv(q)
% helper function for the combine* functions, defining the results
% variables to examine
%
%                         >>> INPUT VARIABLES >>>
% NAME            TYPE/DEFAULT          DESCRIPTION
% q               char arr              'auto' or 'cross'
%                     
%                         <<< OUTPUT VARIABLES <<<
%
% NAME            TYPE/DEFAULT           DESCRIPTION
% rv              cell arr of char arrs  results variables to examine 
%                                        (must be field names of r)
% rvix            array or char, 'all'   indices to subset of pars currently of
%                                        interest


rvix='all';

switch q
  case 'auto'
    % all that make sense as autos 
    rv_commented={...
      'detheCCPeakMn', 'delta & theta envelope, peak crosscorrelation, dimensionless';...
      'detheCCPeakTMn', 'delta & theta envelope, lag at peak crosscorrelation, ms';...
      'thgaeCCPeakMn', 'theta & gamma envelope, peak crosscorrelation, dimensionless';...
      'thgaeCCPeakStd', 'theta & gamma envelope, peak crosscorrelation, dimensionless';...
      'thgaeCCPeakTMn', 'theta & gamma envelope, lag at peak crosscorrelation, ms';...
      'thgaeCCPeakTStd', 'theta & gamma envelope, lag at peak crosscorrelation, ms';...
      'thgaeCCPeakPhaseMn', 'theta & gamma envelope, lag of peak crosscorrelation, radians';...            
      'thgaeCCPeakPhaseStd', 'theta & gamma envelope, lag of peak crosscorrelation, radians';...            
      'thgaeCCZScore', 'theta & gamma envelope, Z-score of peak crosscorrelation, dimensionless';...
      'thgaeCCZTestP', 'theta & gamma envelope, p-value of peak crosscorrelation, dimensionless';...
      'thgaeCCPosPeakDecayMn', 'theta & gamma envelope, height of largest side peak in their correlation, dimensionless';...
      'thgaeCCPosPeakDecayStd', 'theta & gamma envelope, height of largest side peak in their correlation, dimensionless';...
      'thgaeCCEnvPeakMn', 'theta & gamma envelope, peak of envelope of crosscorrelation, dimensionless';...
      'thgaeCCEnvPeakStd', 'theta & gamma envelope, peak of envelope of crosscorrelation, dimensionless';...
      'thgaeCCEnvPeakTMn', 'theta & gamma envelope, lag at peak of envelope of crosscorrelation, ms';...
      'thgaeCCEnvPeakTStd', 'theta & gamma envelope, lag at peak of envelope of crosscorrelation, ms';...
      'thgaeCCEnvPeakPhaseMn', 'theta & gamma envelope, lag of peak of envelope of crosscorrelation, radians';...            
      'thgaeCCEnvPeakPhaseStd', 'theta & gamma envelope, lag of peak of envelope of crosscorrelation, radians';...            
      'thgaeCCEnvZScore', 'theta & gamma envelope, Z-score of peak of envelope of crosscorrelation, dimensionless';...
      'thgaeCCEnvZTestP', 'theta & gamma envelope, p-value of peak of envelope of crosscorrelation, dimensionless';...
      'rawPPeakMn', 'theta, peaks of individual (segmental) power spectra, averaged, mV^2/Hz';...
      'rawPPeakTMn', 'theta, frequency of peaks of individual (segmental) power spectra, averaged, Hz';...
      'rawPMnPeak', 'theta, peak of averaged power spectra, mV^2/Hz';...
      'rawPMnPeakT', 'theta, frequency peak of averaged power spectra, mV^2/Hz';...
      'rawPSEFMn', 'spectral edge frequency, Hz';...
      'rawDePEMn', 'delta, power, mV^2';...
      'rawThPEMn', 'theta, power, mV^2';...
      'rawThNarrowPEMn', 'narrow band of theta (peak freq +/-1 Hz), power, mV^2';...
      'rawBePEMn', 'beta, power, mV^2';...
      'rawGaPEMn', 'gamma, power, mV^2';...
      'rawGaNarrowPEMn', 'narrow band of gamma, power, mV^2';...      
      'rawRiPEMn', 'ripples, power, mV^2';...
      'rawGaCentroidMn','gamma, centroid (frequency weighted by power in each freq bin), Hz';...
      'thCCPosPeakDecayMn', 'theta, height of largest side peak in autocorrelation, dimensionless';...
      'thPosPeakCvAMn', 'theta, coefficient of variation of positive peak amplitude, dimensionless';...
      'thPosPeakCvIPIMn', 'theta, coefficient of variation of positive peak inter-peak-interval, dimensionless';...
      'thNegPeakCvAMn', 'theta, coefficient of variation of negative peak amplitude, dimensionless';...
      'thNegPeakCvIPIMn', 'theta, coefficient of variation of negative peak inter-peak-interval, dimensionless';...
      'gaePosPeakCvAMn', 'gamma envelope, coefficient of variation of positive peak amplitude, dimensionless';...
      'gaePosPeakCvIPIMn', 'gamma envelope, coefficient of variation of positive peak inter-peak-interval, dimensionless';...
      'gaeNegPeakCvAMn', 'gamma envelope, coefficient of variation of negative peak amplitude, dimensionless';...
      'gaeNegPeakCvIPIMn', 'gamma envelope, coefficient of variation of negative peak inter-peak-interval, dimensionless';...
      'gaePPeakMn', 'gamma envelope, peaks of individual (segmental) power spectra, averaged, mV^2/Hz';...
      'gaePPeakTMn', 'gamma envelope, frequency of peaks of individual (segmental) power spectra, Hz';...
      'gaePMnPeak', 'gamma envelope, peak of averaged power spectra, mV^2/Hz';...
      'gaePMnPeakT', 'gamma envelope, frequency peak of averaged power spectra, mV^2/Hz';...
      'gaeThPEMn', 'gamma envelope, power in theta band, mV^2';...
      'gaeThNarrowPEMn', 'gamma envelope, power in narrow theta band, mV^2';...
      'rawgaeCohPeak', 'raw & gamma envelope, amplitude peak of coherence in theta band, dimensionless';...
      'rawgaeCohPeakF', 'raw & gamma envelope, frequency at peak of coherence in theta band, dimensionless';...
      'rawgaeCohTh', 'raw & gamma envelope, integral of coherence in theta band, dimensionless';...
      };

    % currently of interest
    rv_commented={...
      'thgaeCCPeakMn', 'theta & gamma envelope, peak crosscorrelation, dimensionless';...
      'thgaeCCPeakStd', 'theta & gamma envelope, peak crosscorrelation, dimensionless';...
      'thgaeCCPeakTMn', 'theta & gamma envelope, lag at peak crosscorrelation, ms';...
      'thgaeCCPeakTStd', 'theta & gamma envelope, lag at peak crosscorrelation, ms';...
      'thgaeCCPeakPhaseMn', 'theta & gamma envelope, lag of peak crosscorrelation, radians';...            
      'thgaeCCPeakPhaseStd', 'theta & gamma envelope, lag of peak crosscorrelation, radians';...            
      'thgaeCCZScore', 'theta & gamma envelope, Z-score of peak crosscorrelation, dimensionless';...
      'thgaeCCZTestP', 'theta & gamma envelope, p-value of peak crosscorrelation, dimensionless';...
      'rawPPeakMn', 'theta, peaks of individual (segmental) power spectra, averaged, mV^2/Hz';...
      'rawPPeakTMn', 'theta, frequency of peaks of individual (segmental) power spectra, Hz';...
      'rawPMnPeak', 'theta, peak of averaged power spectra, mV^2/Hz';...
      'rawPMnPeakT', 'theta, frequency peak of averaged power spectra, mV^2/Hz';...
      'rawDePEMn', 'delta, power, mV^2';...
      'rawThPEMn', 'theta, power, mV^2';...
      'rawThNarrowPEMn', 'narrow band of theta (peak freq +/-1 Hz), power, mV^2';...
      'rawBePEMn', 'beta, power, mV^2';...
      'rawGaPEMn', 'gamma, power, mV^2';...
      'rawGaNarrowPEMn', 'narrow band of gamma, power, mV^2';...      
      'rawRiPEMn', 'ripples, power, mV^2';...
      'rawGaCentroidMn','gamma, centroid (frequency weighted by power in each freq bin), Hz';...
      'thCCPosPeakDecayMn', 'theta, height of largest side peak in autocorrelation, dimensionless';...
      'thPosPeakCvAMn', 'theta, coefficient of variation of positive peak amplitude, dimensionless';...
      'thPosPeakCvIPIMn', 'theta, coefficient of variation of positive peak inter-peak-interval, dimensionless';...
      'thNegPeakCvAMn', 'theta, coefficient of variation of negative peak amplitude, dimensionless';...
      'thNegPeakCvIPIMn', 'theta, coefficient of variation of negative peak inter-peak-interval, dimensionless';...
      'gaePosPeakCvAMn', 'gamma envelope, coefficient of variation of positive peak amplitude, dimensionless';...
      'gaePosPeakCvIPIMn', 'gamma envelope, coefficient of variation of positive peak inter-peak-interval, dimensionless';...
      'gaeNegPeakCvAMn', 'gamma envelope, coefficient of variation of negative peak amplitude, dimensionless';...
      'gaeNegPeakCvIPIMn', 'gamma envelope, coefficient of variation of negative peak inter-peak-interval, dimensionless';...
      'gaePPeakMn', 'gamma envelope, peaks of individual (segmental) power spectra, averaged, mV^2/Hz';...
      'gaePPeakTMn', 'gamma envelope, frequency of peaks of individual (segmental) power spectra, Hz';...
      'gaePMnPeak', 'gamma envelope, peak of averaged power spectra, mV^2/Hz';...
      'gaePMnPeakT', 'gamma envelope, frequency peak of averaged power spectra, mV^2/Hz';...
      'gaeThPEMn', 'gamma envelope, power in theta band, mV^2';...
      'gaeThNarrowPEMn', 'gamma envelope, power in narrow theta band, mV^2';...
      'rawgaeCohPeak', 'raw & gamma envelope, amplitude peak of coherence in theta band, dimensionless';...
      'rawgaeCohPeakF', 'raw & gamma envelope, frequency at peak of coherence in theta band, dimensionless';...
      'rawgaeCohTh', 'raw & gamma envelope, integral of coherence in theta band, dimensionless';...
      };

    rvix='all';

    
  case 'cross'
    % all that make sense as cross-measures
    rv_commented={...
      'deCCPeakMn', 'delta, peak crosscorrelation, dimensionless';...
      'deCCPeakTMn', 'delta, lag of peak crosscorrelation, ms';...
      'thCCPeakMn', 'theta, peak crosscorrelation, dimensionless';...
      'thCCPeakStd', 'theta, peak crosscorrelation, dimensionless';...
      'thCCPeakTMn', 'theta, lag of peak crosscorrelation, ms';...
      'thCCPeakTStd', 'theta, lag of peak crosscorrelation, ms';...
      'thCCPeakPhaseMn', 'theta, lag of peak crosscorrelation, radians';...
      'thCCPeakPhaseStd', 'theta, lag of peak crosscorrelation, radians';...
      'gaCCPeakMn', 'gamma, peak crosscorrelation, dimensionless';...
      'gaCCPeakStd', 'gamma, peak crosscorrelation, dimensionless';...
      'gaCCPeakTMn', 'gamma, lag of peak crosscorrelation, ms';...
      'gaCCPeakTStd', 'gamma, lag of peak crosscorrelation, ms';...
      'thHieCCPeakMn', 'theta hi, peak crosscorrelation, dimensionless';...
      'thHieCCPeakTMn', 'theta hi, lag of peak crosscorrelation, ms';...
      'thLoeCCPeakMn', 'theta lo, peak crosscorrelation, dimensionless';...
      'thLoeCCPeakTMn', 'theta lo, lag of peak crosscorrelation, ms';...
      'gaeCCPeakMn', 'gamma envelope, peak crosscorrelation, dimensionless';...
      'gaeCCPeakStd', 'gamma envelope, peak crosscorrelation, dimensionless';...
      'gaeCCPeakTMn', 'gamma envelope, lag of peak crosscorrelation, ms';...
      'gaeCCPeakTStd', 'gamma envelope, lag of peak crosscorrelation, ms';...      
      'gaeCCPeakPhaseMn', 'gamma envelope, lag of peak crosscorrelation, radians';...      
      'gaeCCPeakPhaseStd', 'gamma envelope, lag of peak crosscorrelation, radians';...      
      'rawPPeakMn', 'theta, peaks of individual (segmental) cross spectra, averaged, mV^2/Hz';...
      'rawPPeakTMn', 'theta, frequency of peaks of individual (segmental) cross spectra, Hz';...
      'rawPMnPeak', 'theta, peak of averaged cross spectra, mV^2/Hz';...
      'rawPMnPeakT', 'theta, frequency peak of averaged cross spectra, mV^2/Hz';...
      'rawPSEFMn', 'spectral edge frequency, Hz';...
      'rawCohMnDe', 'delta, coherence, dimensionless';...
      'rawCohMnTh', 'theta, coherence, dimensionless';...
      'rawCohMnThNarrow', 'narrow band of theta, coherence, dimensionless';...
      'rawCohMnBe', 'beta, coherence, dimensionless';...
      'rawCohMnGa', 'gamma, coherence, dimensionless';...
      'rawCohMnGaNarrow', 'narrow band of gamma, coherence, dimensionless';...
      'rawCohMnRi', 'ripples, coherence, dimensionless';...
      'rawDePEMn', 'delta, power, mV^2';...
      'rawThPEMn', 'theta, power, mV^2';...
      'rawThNarrowPEMn', 'narrow band of theta (peak freq +/-1 Hz), power, mV^2';...
      'rawBePEMn', 'beta, power, mV^2';...
      'rawGaPEMn', 'gamma, power, mV^2';...
      'rawGaNarrowPEMn', 'narrow band of gamma, power, mV^2';...      
      'rawRiPEMn', 'ripples, power, mV^2';...
      'rawGaCentroidMn','gamma, centroid (frequency weighted by power in each freq bin), Hz';...
      'gaeCohMnTh', 'gamma envelope, coherence in theta range, dimensionless';...
      'gaeCohMnThNarrow', 'gamma envelope, coherence in narrow theta range, dimensionless';...
      'gaeCohMnDe', 'gamma envelope, coherence in delta range, dimensionless';...
      'rawgaeCohPeak', 'raw & gamma envelope, amplitude peak of coherence in theta band, dimensionless';...
      'rawgaeCohPeakF', 'raw & gamma envelope, frequency at peak of coherence in theta band, dimensionless';...
      'rawgaeCohTh', 'raw & gamma envelope, integral of coherence in theta band, dimensionless';...
      };
    
    % currently of interest
    rv_commented={...
      'thCCPeakMn', 'theta, peak crosscorrelation, dimensionless';...
      'thCCPeakStd', 'theta, peak crosscorrelation, dimensionless';...
      'thCCPeakTMn', 'theta, lag of peak crosscorrelation, ms';...
      'thCCPeakTStd', 'theta, lag of peak crosscorrelation, ms';...
      'thCCPeakPhaseMn', 'theta, lag of peak crosscorrelation, radians';...
      'thCCPeakPhaseStd', 'theta, lag of peak crosscorrelation, radians';...
      'gaCCPeakMn', 'gamma, peak crosscorrelation, dimensionless';...
      'gaCCPeakStd', 'gamma, peak crosscorrelation, dimensionless';...
      'gaCCPeakTMn', 'gamma, lag of peak crosscorrelation, ms';...
      'gaCCPeakTStd', 'gamma, lag of peak crosscorrelation, ms';...
      'gaeCCPeakMn', 'gamma envelope, peak crosscorrelation, dimensionless';...
      'gaeCCPeakStd', 'gamma envelope, peak crosscorrelation, dimensionless';...
      'gaeCCPeakTMn', 'gamma envelope, lag of peak crosscorrelation, ms';...
      'gaeCCPeakTStd', 'gamma envelope, lag of peak crosscorrelation, ms';...      
      'gaeCCPeakPhaseMn', 'gamma envelope, lag of peak crosscorrelation, radians';...      
      'gaeCCPeakPhaseStd', 'gamma envelope, lag of peak crosscorrelation, radians';...      
      'rawCohMnDe', 'delta, coherence, dimensionless';...
      'rawCohMnTh', 'theta, coherence, dimensionless';...
      'rawCohMnThNarrow', 'narrow band of theta, coherence, dimensionless';...
      'rawCohMnBe', 'beta, coherence, dimensionless';...
      'rawCohMnGa', 'gamma, coherence, dimensionless';...
      'rawCohMnGaNarrow', 'narrow band of gamma, coherence, dimensionless';...
      'rawCohMnRi', 'ripples, coherence, dimensionless';...
      'gaeCohMnTh', 'gamma envelope, coherence in theta range, dimensionless';...
      'gaeCohMnThNarrow', 'gamma envelope, coherence in narrow theta range, dimensionless';...
      'gaeCohMnDe', 'gamma envelope, coherence in delta range, dimensionless';...
      'rawgaeCohPeak', 'raw & gamma envelope, amplitude peak of coherence in theta band, dimensionless';...
      'rawgaeCohPeakF', 'raw & gamma envelope, frequency at peak of coherence in theta band, dimensionless';...
      'rawgaeCohTh', 'raw & gamma envelope, integral of coherence in theta band, dimensionless';...
      };

    rvix='all';
end

rv=rv_commented(:,1);